name: rpk
matrix:
  architectures:
    - amd64
    - arm64
  versions:
    - 24.1.8
    - 24.1.9
    - 24.1.10
    - 24.1.11
    - 24.1.12
    - 24.1.13
    - 24.2.1
    - 24.2.2
    - 24.2.3
    - 24.2.4
    - 24.2.5
    - 24.2.6
    - 24.2.7
    - 24.2.8
    - 24.2.9
    - 24.2.10
    - 24.2.11
    - 24.2.12
    - 24.3.1
    - 24.3.2
    - 24.3.3
    - 24.3.4
    - 24.3.5
    - 24.3.6
    - 24.3.7
    - 24.3.8
    - 24.3.9
    - 25.1.1
    - 25.1.2
    - 25.1.3
    - 25.1.5
    - 25.1.6
    - 25.1.7
    - 25.1.8
    - 25.1.9
    - 25.2.1
    - 25.2.2
    - 25.2.3
    - 25.2.4
    - 25.2.5
    - 25.2.6
    - 25.2.7
    - 25.2.8
    - 25.2.9
    - 25.2.10
    - 25.3.1
    - 25.3.2
    - 25.3.3
    - 25.3.4
    - 25.3.5
homepage: https://redpanda.com/
summary: interact with your Redpanda clusters
description: |-
  Redpanda is a streaming data platform for developers. Kafka API compatible. 10x
  faster. No ZooKeeper. No JVM!
fetch: https://github.com/redpanda-data/redpanda/releases/download/v{{version}}/rpk-linux-{{arch}}.zip
install:
  - rpk:/usr/bin/rpk
