name: krew
matrix:
  architectures:
    - amd64
    - arm64
    - armhf
  versions:
    - 0.4.3
    - 0.4.4
    - 0.4.5
    - 0.5.0
homepage: https://krew.sigs.k8s.io
summary: find and install kubectl plugins
description: Krew is the package manager for kubectl plugins.
fetch: https://github.com/kubernetes-sigs/krew/releases/download/v{{version}}/krew-linux_{{goarch}}.tar.gz
install:
  - krew-linux_{{goarch}}:/usr/bin/krew
