name: cloud-provider-kind
matrix:
  versions:
    - 0.8.0
    - 0.9.0
homepage: https://github.com/kubernetes-sigs/cloud-provider-kind
summary: Kubernetes Cloud Provider for KIND
description: |-
  KIND has demonstrated to be a very versatile, efficient, cheap and very useful
  tool for Kubernetes testing.
  However, KIND doesn't offer capabilities for testing all the features that
  depend on cloud-providers,
  specifically the Load Balancers, causing a gap on testing and a bad user
  experience,
  since is not easy to connect to the applications running on the cluster.

  cloud-provider-kind aims to fill this gap and provide an agnostic and cheap
  solution for all
  the Kubernetes features that depend on a cloud-provider using KIND.
fetch: https://github.com/kubernetes-sigs/cloud-provider-kind/releases/download/v{{version}}/cloud-provider-kind_{{version}}_linux_amd64.tar.gz
install:
  - cloud-provider-kind:/usr/bin/
