name: dapr
matrix:
  architectures:
    - amd64
    - arm64
  versions:
    - 1.12.0
    - 1.13.0
    - 1.14.0
    - 1.14.1
    - 1.15.0
    - 1.15.1
    - 1.15.2
    - 1.16.0
    - 1.16.1
    - 1.16.2
    - 1.16.3
homepage: https://dapr.io/
summary: command-line tools for Dapr.
description: |-
  Allows you to setup Dapr on your local dev machine or on a Kubernetes cluster,
  provides debugging support, launches and manages Dapr instances.
fetch: https://github.com/dapr/cli/releases/download/v{{version}}/dapr_linux_{{goarch}}.tar.gz
install:
  - dapr:/usr/bin/dapr
