name: iamlive
matrix:
  architectures:
    - amd64
    - arm64
  versions:
    - 0.44.0
    - 0.45.0
    - 0.46.0
    - 0.47.3
    - 0.48.0
    - 0.49.0
    - 0.50.0
    - 0.51.0
    - 0.51.1
    - 0.51.2
    - 0.52.0
    - 0.53.0
    - 1.1.0
    - 1.1.1
    - 1.1.2
    - 1.1.3
    - 1.1.4
    - 1.1.5
    - 1.1.6
    - 1.1.7
    - 1.1.8
    - 1.1.9
    - 1.1.10
    - 1.1.11
    - 1.1.12
    - 1.1.13
    - 1.1.14
    - 1.1.15
    - 1.1.16
    - 1.1.18
    - 1.1.19
    - 1.1.22
homepage: https://github.com/iann0036/iamlive
summary: generate policies from AWS calls
description: |-
  Generate an IAM policy from AWS calls using client-side monitoring (CSM) or
  embedded proxy policy.
fetch: https://github.com/iann0036/iamlive/releases/download/v{{version}}/iamlive-v{{version}}-linux-{{goarch}}.tar.gz
install:
  - iamlive:/usr/bin/iamlive
