- name: skaffold
  matrix:
    versions:
      - 1.35.2
      - 1.35.0
  homepage: https://skaffold.dev/
  summary: easy and repeatable Kubernetes development
  description: |-
    Command line tool that facilitates continuous development for Kubernetes
    applications.
    You can iterate on your application source code locally then deploy to local or
    remote Kubernetes clusters. Skaffold handles the workflow for building,
    pushing and deploying your application. It also provides building blocks
    and describe customizations for a CI/CD pipeline.
  fetch: https://github.com/GoogleContainerTools/skaffold/releases/download/v{{version}}/skaffold-linux-amd64
  script:
    - mv skaffold-linux-amd64 {{src}}/usr/bin/skaffold

- name: skaffold
  matrix:
    architectures:
      - arm64
      - amd64
    versions:
      - 1.35.2
      - 1.35.0
      - 1.36.0
      - 1.37.0
      - 1.37.1
  homepage: https://skaffold.dev/
  summary: easy and repeatable Kubernetes development
  description: |-
    Command line tool that facilitates continuous development for Kubernetes
    applications.
    You can iterate on your application source code locally then deploy to local or
    remote Kubernetes clusters. Skaffold handles the workflow for building,
    pushing and deploying your application. It also provides building blocks
    and describe customizations for a CI/CD pipeline.
  fetch: https://github.com/GoogleContainerTools/skaffold/releases/download/v{{version}}/skaffold-linux-{{goarch}}
  script:
    - mv skaffold-linux-{{goarch}} {{src}}/usr/bin/skaffold

- name: skaffold
  matrix:
    architectures:
      - amd64
      - arm64
    versions:
      - 1.38.0
      - 1.39.0
      - 1.39.1
      - 1.39.2
      - 2.0.0
      - 2.0.1
      - 2.0.2
      - 2.0.3
      - 2.0.4
      - 2.0.5
      - 2.1.0
      - 2.2.0
      - 2.3.0
      - 2.3.1
      - 2.4.0
      - 2.4.1
      - 2.5.0
      - 2.5.1
      - 2.6.0
      - 2.6.1
      - 2.6.2
      - 2.6.3
      - 2.7.0
      - 2.7.1
      - 2.8.0
      - 2.9.0
      - 2.10.0
      - 2.10.1
      - 2.11.0
      - 2.11.1
      - 2.12.0
      - 2.13.0
      - 2.13.1
      - 2.13.2
  homepage: https://skaffold.dev/
  summary: easy and repeatable Kubernetes development
  description: |-
    Command line tool that facilitates continuous development for Kubernetes
    applications.
    You can iterate on your application source code locally then deploy to local or
    remote Kubernetes clusters. Skaffold handles the workflow for building,
    pushing and deploying your application. It also provides building blocks
    and describe customizations for a CI/CD pipeline.
  fetch: https://github.com/GoogleContainerTools/skaffold/releases/download/v{{version}}/skaffold-linux-{{goarch}}
  install:
    - skaffold-linux-{{goarch}}:/usr/bin/skaffold
