- name: kubeseal
  version: 0.16.0
  revision: "3"
  homepage: https://github.com/bitnami-labs/sealed-secrets
  summary: secret management solution for Kubernetes
  description: |-
    Encrypt your Secret into a SealedSecret, which is safe to store - even to a
    public repository.
  fetch: 
    https://github.com/bitnami-labs/sealed-secrets/releases/download/v{{version}}/kubeseal-linux-amd64
  script:
    - mv kubeseal-linux-amd64 {{src}}/usr/bin/kubeseal

- name: kubeseal
  matrix:
    architectures:
      - amd64
      - arm64
      - armhf
    versions:
      - 0.17.3
      - 0.17.4
  homepage: https://github.com/bitnami-labs/sealed-secrets
  summary: secret management solution for Kubernetes
  description: |-
    Encrypt your Secret into a SealedSecret, which is safe to store - even to a
    public repository.
  fetch: 
    https://github.com/bitnami-labs/sealed-secrets/releases/download/v{{version}}/kubeseal-{{version}}-linux-{{goarch}}.tar.gz
  script:
    - mv kubeseal {{src}}/usr/bin/kubeseal

- name: kubeseal
  matrix:
    architectures:
      - amd64
      - arm64
      - armhf
    versions:
      - 0.17.5
      - 0.18.0
      - 0.18.1
      - 0.18.2
      - 0.18.3
      - 0.18.4
      - 0.18.5
      - 0.19.0
      - 0.19.1
      - 0.19.2
      - 0.19.3
      - 0.19.4
      - 0.19.5
      - 0.20.1
      - 0.20.2
      - 0.20.3
      - 0.20.4
      - 0.20.5
      - 0.21.0
      - 0.22.0
      - 0.23.0
      - 0.23.1
      - 0.24.0
      - 0.24.1
      - 0.24.2
      - 0.24.3
      - 0.24.4
      - 0.24.5
      - 0.25.0
      - 0.26.0
      - 0.26.1
      - 0.26.2
      - 0.26.3
      - 0.27.0
      - 0.27.1
      - 0.27.2
      - 0.27.3
      - 0.28.0
      - 0.29.0
  homepage: https://github.com/bitnami-labs/sealed-secrets
  summary: secret management solution for Kubernetes
  description: |-
    Encrypt your Secret into a SealedSecret, which is safe to store - even to a
    public repository.
  fetch: 
    https://github.com/bitnami-labs/sealed-secrets/releases/download/v{{version}}/kubeseal-{{version}}-linux-{{goarch}}.tar.gz
  install:
    - kubeseal:/usr/bin/
