name: jfrog-cli
matrix:
  architectures:
    - amd64
    - arm64
  versions:
    - 2.69.0
    - 2.70.0
    - 2.71.0
    - 2.71.1
    - 2.71.2
    - 2.71.3
    - 2.71.4
    - 2.71.5
    - 2.72.0
    - 2.72.1
    - 2.72.2
    - 2.72.3
    - 2.72.4
    - 2.72.5
    - 2.73.0
    - 2.73.2
    - 2.73.3
    - 2.74.0
    - 2.74.1
    - 2.75.0
    - 2.75.1
    - 2.76.0
    - 2.76.1
    - 2.77.0
    - 2.78.0
    - 2.78.1
    - 2.78.2
    - 2.78.3
    - 2.78.4
    - 2.78.5
    - 2.78.6
    - 2.78.7
    - 2.78.8
    - 2.78.9
    - 2.78.10
    - 2.79.0
    - 2.79.1
    - 2.79.2
    - 2.80.0
    - 2.81.0
    - 2.82.0
    - 2.83.0
    - 2.84.0
    - 2.85.0
    - 2.86.0
    - 2.87.0
    - 2.88.0
    - 2.89.0
    - 2.90.0
    - 2.91.0
homepage: https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli
summary: client that provides a simple interface that automates access to the JFrog
  products
description: |-
  JFrog CLI is a compact and smart client that provides a simple interface that
  automates access to Artifactory and Mission Control through their respective
  REST APIs. By using the JFrog CLI, you can greatly simplify your automation
  scripts making them more readable and easier to maintain.
fetch: https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/{{version}}/jfrog-cli-linux-{{arch}}/jf
install:
  - jf:/usr/bin/
