- name: helm
  matrix:
    architectures:
      - amd64
      - arm64
      - armhf
  version: 3.7.2
  revision: "2"
  homepage: https://helm.sh
  summary: Kubernetes package manager
  description: |-
    Tool for managing Kubernetes charts.
    Charts are packages of pre-configured Kubernetes resources.
  fetch: https://get.helm.sh/helm-v{{version}}-linux-{{goarch}}.tar.gz
  install:
    - linux-{{goarch}}/helm:/usr/bin/

- name: helm
  matrix:
    architectures:
      - amd64
      - arm64
      - armhf
    versions:
      - 3.8.0
      - 3.8.1
      - 3.8.2
      - 3.9.0
      - 3.9.1
  homepage: https://helm.sh
  summary: Kubernetes package manager
  description: |-
    Tool for managing Kubernetes charts.
    Charts are packages of pre-configured Kubernetes resources.
  fetch: https://get.helm.sh/helm-v{{version}}-linux-{{goarch}}.tar.gz
  install:
    - linux-{{goarch}}/helm:/usr/bin/

- name: helm
  matrix:
    architectures:
      - amd64
      - armhf
    versions:
      - 3.9.2
      - 3.9.3
      - 3.9.4
      - 3.10.0
      - 3.10.1
      - 3.10.2
      - 3.10.3
      - 3.11.0
      - 3.11.1
      - 3.11.2
      - 3.11.3
      - 3.12.0
      - 3.12.1
      - 3.12.2
      - 3.12.3
      - 3.13.0
      - 3.13.1
      - 3.13.2
      - 3.13.3
      - 3.14.0
      - 3.14.1
      - 3.14.2
      - 3.14.3
      - 3.14.4
      - 3.15.0
      - 3.15.1
      - 3.15.2
      - 3.15.3
      - 3.15.4
      - 3.16.0
      - 3.16.1
      - 3.16.2
      - 3.16.3
      - 3.16.4
      - 3.17.0
      - 3.17.1
      - 3.17.2
      - 3.17.3
      - 3.18.0
      - 3.18.1
      - 3.18.2
      - 3.18.3
  homepage: https://helm.sh
  summary: Kubernetes package manager
  description: |-
    Tool for managing Kubernetes charts.
    Charts are packages of pre-configured Kubernetes resources.
  fetch: https://get.helm.sh/helm-v{{version}}-linux-{{goarch}}.tar.gz
  install:
    - linux-{{goarch}}/helm:/usr/bin/
