- name: act
  matrix:
    architectures:
      - amd64
      - arm64
      - armhf
  version: 0.2.42
  revision: "2"
  homepage: https://github.com/nektos/act/
  summary: run your GitHub Actions locally
  description: |-
    Why would you want to do this? Two reasons:

    - Fast Feedback: Rather than having to commit/push every time you want to test
    out the changes you are making to your .github/workflows/ files (or for any
    changes to embedded GitHub actions), you can use act to run the actions
    locally. The environment variables and filesystem are all configured to match
    what GitHub provides.
    - Local Task Runner: With act, you can use the GitHub Actions defined in your
    .github/workflows/ to replace your Makefile!
  fetch:
    url: https://github.com/nektos/act/releases/download/v{{version}}/act_Linux_{{target}}.tar.gz
    targets:
      amd64: x86_64
      armhf: armv7
  install:
    - act:/usr/bin/act

- name: act
  matrix:
    architectures:
      - amd64
      - arm64
      - armhf
    versions:
      - 0.2.43
      - 0.2.44
      - 0.2.45
      - 0.2.46
      - 0.2.48
      - 0.2.49
      - 0.2.50
      - 0.2.51
      - 0.2.52
      - 0.2.53
      - 0.2.54
      - 0.2.55
      - 0.2.56
      - 0.2.57
      - 0.2.59
      - 0.2.60
      - 0.2.61
      - 0.2.62
      - 0.2.63
      - 0.2.64
      - 0.2.65
      - 0.2.66
      - 0.2.67
      - 0.2.68
      - 0.2.69
      - 0.2.70
      - 0.2.71
      - 0.2.72
      - 0.2.73
      - 0.2.74
      - 0.2.75
      - 0.2.76
      - 0.2.77
      - 0.2.78
      - 0.2.79
  homepage: https://github.com/nektos/act/
  summary: run your GitHub Actions locally
  description: |-
    Why would you want to do this? Two reasons:

    - Fast Feedback: Rather than having to commit/push every time you want to test
    out the changes you are making to your .github/workflows/ files (or for any
    changes to embedded GitHub actions), you can use act to run the actions
    locally. The environment variables and filesystem are all configured to match
    what GitHub provides.
    - Local Task Runner: With act, you can use the GitHub Actions defined in your
    .github/workflows/ to replace your Makefile!
  fetch:
    url: https://github.com/nektos/act/releases/download/v{{version}}/act_Linux_{{target}}.tar.gz
    targets:
      amd64: x86_64
      armhf: armv7
  install:
    - act:/usr/bin/act
