- name: devspace
  version: 5.16.2
  homepage: https://devspace.sh
  summary: developer tool for Kubernetes
  description: |-
    Automate your deployment workflow with DevSpace and develop software directly
    inside Kubernetes.
  fetch: https://github.com/loft-sh/devspace/releases/download/v{{version}}/devspace-linux-amd64
  script:
    - install -m 755 devspace-linux-amd64 {{src}}/usr/bin/devspace

- name: devspace
  version: 5.17.0
  revision: "2"
  homepage: https://devspace.sh
  summary: developer tool for Kubernetes
  description: |-
    Automate your deployment workflow with DevSpace and develop software directly
    inside Kubernetes.
  fetch: https://github.com/loft-sh/devspace/releases/download/v{{version}}/devspace-linux-amd64
  script:
    - install -m 755 devspace-linux-amd64 {{src}}/usr/bin/devspace

- name: devspace
  matrix:
    architectures:
      - amd64
      - arm64
    versions:
      - 5.18.3
      - 5.18.4
      - 5.18.5
      - 6.0.0
      - 6.0.1
      - 6.1.0
      - 6.1.1
      - 6.2.0
      - 6.2.1
      - 6.2.2
      - 6.2.3
      - 6.2.4
      - 6.2.5
  homepage: https://devspace.sh
  summary: developer tool for Kubernetes
  description: |-
    Automate your deployment workflow with DevSpace and develop software directly
    inside Kubernetes.
  fetch: https://github.com/loft-sh/devspace/releases/download/v{{version}}/devspace-linux-{{goarch}}
  install:
    - devspace-linux-{{goarch}}:/usr/bin/devspace

- name: devspace
  matrix:
    architectures:
      - amd64
      - arm64
    versions:
      - 6.3.0
      - 6.3.1
      - 6.3.2
      - 6.3.3
      - 6.3.4
      - 6.3.5
      - 6.3.6
      - 6.3.7
      - 6.3.8
      - 6.3.9
      - 6.3.10
      - 6.3.11
      - 6.3.12
      - 6.3.13
      - 6.3.14
      - 6.3.15
      - 6.3.16
      - 6.3.17
  homepage: https://devspace.sh
  summary: developer tool for Kubernetes
  description: |-
    Automate your deployment workflow with DevSpace and develop software directly
    inside Kubernetes.
  fetch: https://github.com/devspace-sh/devspace/releases/download/v{{version}}/devspace-linux-{{goarch}}
  install:
    - devspace-linux-{{goarch}}:/usr/bin/devspace
