- name: telepresence
  matrix:
    architectures:
      - amd64
      - arm64
    versions:
      - 2.5.3
      - 2.5.4
  homepage: https://www.telepresence.io/
  summary: fast, local development for kubernetes and openshift microservices
  description: |-
    Open source tool that lets you run a single service locally, while connecting
    that service to a remote Kubernetes cluster. This lets developers working on
    multi-service applications to:

    - Do fast local development of a single service, even if that service depends
    on other services in your cluster. Make a change to your service, save, and you
    can immediately see the new service in action.
    - Use any tool installed locally to test/debug/edit your service. For example,
    you can use a debugger or IDE!
    - Make your local development machine operate as if it's part of your
    Kubernetes cluster. If you've got an application on your machine that you want
    to run against a service in the cluster -- it's easy to do.
  fetch: https://app.getambassador.io/download/tel2/linux/{{arch}}/{{version}}/telepresence
  script:
    - mv telepresence {{src}}/usr/bin/telepresence

- name: telepresence
  matrix:
    architectures:
      - amd64
      - arm64
    versions:
      - 2.7.3
      - 2.7.4
      - 2.7.5
      - 2.7.6
      - 2.8.0
      - 2.8.1
      - 2.8.2
      - 2.8.3
      - 2.8.5
      - 2.9.1
      - 2.9.2
      - 2.9.3
      - 2.9.4
      - 2.9.5
      - 2.10.0
      - 2.10.1
      - 2.10.2
      - 2.10.3
      - 2.10.4
      - 2.10.5
      - 2.10.6
      - 2.11.0
      - 2.11.1
      - 2.12.0
      - 2.12.1
      - 2.12.2
      - 2.13.0
      - 2.13.1
      - 2.13.2
      - 2.13.3
      - 2.14.0
      - 2.14.1
      - 2.14.2
      - 2.15.0
      - 2.15.1
      - 2.16.0
      - 2.16.1
      - 2.17.0
      - 2.17.1
      - 2.18.0
      - 2.18.1
      - 2.19.0
      - 2.19.1
      - 2.19.2
      - 2.19.3
      - 2.19.4
      - 2.19.5
      - 2.19.6
      - 2.20.0
      - 2.20.1
  homepage: https://www.telepresence.io/
  summary: fast, local development for kubernetes and openshift microservices
  description: |-
    Open source tool that lets you run a single service locally, while connecting
    that service to a remote Kubernetes cluster. This lets developers working on
    multi-service applications to:

    - Do fast local development of a single service, even if that service depends
    on other services in your cluster. Make a change to your service, save, and you
    can immediately see the new service in action.
    - Use any tool installed locally to test/debug/edit your service. For example,
    you can use a debugger or IDE!
    - Make your local development machine operate as if it's part of your
    Kubernetes cluster. If you've got an application on your machine that you want
    to run against a service in the cluster -- it's easy to do.
  fetch: https://app.getambassador.io/download/tel2/linux/{{arch}}/{{version}}/telepresence
  install:
    - telepresence:/usr/bin/
