name: infracost
matrix:
  architectures:
    - amd64
    - arm64
  versions:
    - 0.10.8
    - 0.10.9
    - 0.10.10
    - 0.10.11
    - 0.10.12
    - 0.10.13
    - 0.10.14
    - 0.10.15
    - 0.10.16
    - 0.10.17
    - 0.10.18
    - 0.10.19
    - 0.10.20
    - 0.10.21
    - 0.10.22
    - 0.10.23
    - 0.10.24
    - 0.10.25
    - 0.10.26
    - 0.10.27
    - 0.10.28
    - 0.10.29
    - 0.10.30
    - 0.10.31
    - 0.10.32
    - 0.10.33
    - 0.10.34
    - 0.10.35
    - 0.10.36
homepage: https://www.infracost.io
summary: cloud cost estimates for Terraform in pull requests
description: |-
  Infracost shows cloud cost estimates for Terraform. It lets DevOps, SRE and
  engineers see a cost breakdown and understand costs before making changes,
  either in the terminal or pull requests.
fetch: https://github.com/infracost/infracost/releases/download/v{{version}}/infracost-linux-{{target}}.tar.gz
install:
  - infracost-linux-{{target}}:/usr/bin/infracost
